

CREATE TABLE workout_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    muscle TEXT NOT NULL,
    exercise TEXT NOT NULL,
    exercise_sets TEXT NOT NULL,
    reps TEXT NOT NULL,
    weight_amount TEXT NOT NULL,
    summary TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
