DROP TABLE IF EXISTS workout_articles;

CREATE TABLE workout_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    muscle TEXT NOT NULL,
    exercise TEXT NOT NULL,
    exercise_sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight_amount INTEGER NOT NULL,
    summary TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    weekday INTEGER NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);
